apiVersion: v1
kind: Service
metadata:
  name: local-webapp-service
spec:
  type: NodePort
  selector:
    app: local-webapp # Must exactly match the matchLabels/labels in your Deployment
  ports:
    - protocol: TCP
      port: 80       # The port the service listens on inside the cluster
      targetPort: 80 # The port your application container is actually listening on
      nodePort: 30080 #
